### ISSUE TITLE
[remark-lint-no-paragraph-content-indent] TypeError when parsing image without "alt" text

### ISSUE THREAD

**Issue by arcticicestudio** [remarkjs/remark-lint#172]
An exception is thrown when a image without an `alt` text is parsed:

```raw
TypeError: Cannot read property 'charAt' of null`
```

As soon as a `alt` text is provided it works fine.

###### `package.json`

```json
{
  "name": "mcve",
  "version": "1.0.0",
  "description": "",
  "dependencies": {
    "remark-cli": "5.0.0",
    "remark-lint": "6.0.1",
    "remark-lint-no-paragraph-content-indent": "1.0.3",
    "remark-preset-lint-arcticicestudio": "0.1.0"
  },
  "devDependencies": {},
  "scripts": {
    "lint": "remark --no-stdout ./*.md"
  }
}
```

###### `.remark.js`

```js
module.exports = {
  plugins: ["remark-preset-lint-arcticicestudio"]
};

```

###### `mcve.md`

```markdown
[![][styleguide-javascript-badge]][styleguide-javascript-github]

[styleguide-javascript-badge]: https://rawgit.com/arcticicestudio/styleguide-javascript/develop/assets/styleguide-javascript-banner-typography-badge.svg
[styleguide-javascript-github]: https://github.com/arcticicestudio/styleguide-javascript

```

Running `npm run lint` now will result in the following exception:

```raw
mcve.md
  1:1  error  TypeError: Cannot read property 'charAt' of null
    at check (/home/arcticicestudio/desktop/mcve/node_modules/remark-lint-no-paragraph-content-indent/index.js:107:46)
    at one (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:31:16)
    at all (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:54:25)
    at one (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:39:14)
    at all (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:54:25)
    at one (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:39:14)
    at visit (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:22:3)
    at visitor (/home/arcticicestudio/desktop/mcve/node_modules/remark-lint-no-paragraph-content-indent/index.js:88:5)
    at one (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:31:16)
    at all (/home/arcticicestudio/desktop/mcve/node_modules/unist-util-visit/index.js:54:25)  no-paragraph-content-indent  remark-lint

```

**Comment by wooorm** [comment]
@arcticicestudio Nice find, and thanks for the detailed example!

Would you be interested in working on a PR?

**Comment by arcticicestudio** [comment]
@wooorm Unfortunately my free time is currently limited to work on OSS 😐. I can try to fix it when there's some time on the weekend, but feel free to assign it to someone else if it should be fixed asap to package a release.

**Comment by Murderlon** [comment]
I am going to work on this somewhere today, should have a PR ready later this afternoon or perhaps in the evening :)

**Comment by arcticicestudio** [comment]
@Murderlon :+1: Thanks for taking over and the nice PR. I planed to work on it last weekend, but study time has been eating all my weekends.
