### ISSUE TITLE
Error in tests

### ISSUE THREAD

**Issue by AlexWayfer** [remarkjs/remark-lint#231]
### Subject of the issue

Hello.

I'm trying to resolve #230 and I can't run tests.

### Your environment

*   **OS**: Arch Linux
*   **Packages**: Just `remark-lint` repo.
*   **Env**: Node v13.13.0, npm 6.14.4, yarn 1.22.4

### Steps to reproduce

I've found "Contributing" section in README:

> See [`contributing.md`][contributing] in [`remarkjs/.github`][health] for ways
to get started.

I've opened this guide: https://github.com/remarkjs/.github/blob/80e5735/contributing.md

And I see:

> Lint and test before submitting code by running `$ npm test`

1. There is no info that dependencies have to be installed (`npm install`).
2. I've tried to install them via `npm` and I got the error:
    ```
    npm WARN deprecated mkdirp-promise@5.0.1: This package is broken and no longer maintained. 'mkdirp' itself supports promises now, please switch to that.
    npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm ERR! cb() never called!

    npm ERR! This is an error with npm itself. Please report this error at:
    npm ERR!     <https://npm.community>

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/alex/.npm/_logs/2020-04-19T12_46_44_009Z-debug.log
    ```
3. `yarn install` works.
4. `yarn test` (or `npm run test`) doesn't work:
    ```
    > yarn test
    yarn run v1.22.4
    $ npm run generate && npm run format && npm run build && npm run test-coverage

    > @ generate /home/alex/Projects/js/remark-lint
    > npm run generate:presets && npm run generate:rules


    > @ generate:presets /home/alex/Projects/js/remark-lint
    > node script/build-presets

    ✓ wrote `readme.md` in `remark-preset-lint-consistent`
    ✓ wrote `readme.md` in `remark-preset-lint-markdown-style-guide`
    ✓ wrote `readme.md` in `remark-preset-lint-recommended`

    > @ generate:rules /home/alex/Projects/js/remark-lint
    > node script/build-rules

    ✓ wrote `readme.md` in `remark-lint-blockquote-indentation`
    ✓ wrote `readme.md` in `remark-lint-checkbox-character-style`
    ✓ wrote `readme.md` in `remark-lint-checkbox-content-indent`
    ✓ wrote `readme.md` in `remark-lint-code-block-style`
    ✓ wrote `readme.md` in `remark-lint-definition-case`
    ✓ wrote `readme.md` in `remark-lint-definition-spacing`
    ✓ wrote `readme.md` in `remark-lint-emphasis-marker`
    ✓ wrote `readme.md` in `remark-lint-fenced-code-flag`
    ✓ wrote `readme.md` in `remark-lint-fenced-code-marker`
    ✓ wrote `readme.md` in `remark-lint-file-extension`
    ✓ wrote `readme.md` in `remark-lint-final-definition`
    ✓ wrote `readme.md` in `remark-lint-final-newline`
    ✓ wrote `readme.md` in `remark-lint-first-heading-level`
    ✓ wrote `readme.md` in `remark-lint-hard-break-spaces`
    ✓ wrote `readme.md` in `remark-lint-heading-increment`
    ✓ wrote `readme.md` in `remark-lint-heading-style`
    ✓ wrote `readme.md` in `remark-lint-linebreak-style`
    ✓ wrote `readme.md` in `remark-lint-link-title-style`
    ✓ wrote `readme.md` in `remark-lint-list-item-bullet-indent`
    ✓ wrote `readme.md` in `remark-lint-list-item-content-indent`
    ✓ wrote `readme.md` in `remark-lint-list-item-indent`
    ✓ wrote `readme.md` in `remark-lint-list-item-spacing`
    ✓ wrote `readme.md` in `remark-lint-maximum-heading-length`
    ✓ wrote `readme.md` in `remark-lint-maximum-line-length`
    ✓ wrote `readme.md` in `remark-lint-no-auto-link-without-protocol`
    ✓ wrote `readme.md` in `remark-lint-no-blockquote-without-marker`
    ✓ wrote `readme.md` in `remark-lint-no-consecutive-blank-lines`
    ✓ wrote `readme.md` in `remark-lint-no-duplicate-defined-urls`
    ✓ wrote `readme.md` in `remark-lint-no-duplicate-definitions`
    ✓ wrote `readme.md` in `remark-lint-no-duplicate-headings`
    ✓ wrote `readme.md` in `remark-lint-no-duplicate-headings-in-section`
    ✓ wrote `readme.md` in `remark-lint-no-emphasis-as-heading`
    ✓ wrote `readme.md` in `remark-lint-no-empty-url`
    ✓ wrote `readme.md` in `remark-lint-no-file-name-articles`
    ✓ wrote `readme.md` in `remark-lint-no-file-name-consecutive-dashes`
    ✓ wrote `readme.md` in `remark-lint-no-file-name-irregular-characters`
    ✓ wrote `readme.md` in `remark-lint-no-file-name-mixed-case`
    ✓ wrote `readme.md` in `remark-lint-no-file-name-outer-dashes`
    ✓ wrote `readme.md` in `remark-lint-no-heading-content-indent`
    ✓ wrote `readme.md` in `remark-lint-no-heading-indent`
    ✓ wrote `readme.md` in `remark-lint-no-heading-like-paragraph`
    ✓ wrote `readme.md` in `remark-lint-no-heading-punctuation`
    ✓ wrote `readme.md` in `remark-lint-no-html`
    ✓ wrote `readme.md` in `remark-lint-no-inline-padding`
    ✓ wrote `readme.md` in `remark-lint-no-literal-urls`
    ✓ wrote `readme.md` in `remark-lint-no-missing-blank-lines`
    ✓ wrote `readme.md` in `remark-lint-no-multiple-toplevel-headings`
    ✓ wrote `readme.md` in `remark-lint-no-paragraph-content-indent`
    ✓ wrote `readme.md` in `remark-lint-no-reference-like-url`
    ✓ wrote `readme.md` in `remark-lint-no-shell-dollars`
    ✓ wrote `readme.md` in `remark-lint-no-shortcut-reference-image`
    ✓ wrote `readme.md` in `remark-lint-no-shortcut-reference-link`
    ✓ wrote `readme.md` in `remark-lint-no-table-indentation`
    ✓ wrote `readme.md` in `remark-lint-no-tabs`
    ✓ wrote `readme.md` in `remark-lint-no-undefined-references`
    ✓ wrote `readme.md` in `remark-lint-no-unneeded-full-reference-image`
    ✓ wrote `readme.md` in `remark-lint-no-unneeded-full-reference-link`
    ✓ wrote `readme.md` in `remark-lint-no-unused-definitions`
    ✓ wrote `readme.md` in `remark-lint-ordered-list-marker-style`
    ✓ wrote `readme.md` in `remark-lint-ordered-list-marker-value`
    ✓ wrote `readme.md` in `remark-lint-rule-style`
    ✓ wrote `readme.md` in `remark-lint-strong-marker`
    ✓ wrote `readme.md` in `remark-lint-table-cell-padding`
    ✓ wrote `readme.md` in `remark-lint-table-pipe-alignment`
    ✓ wrote `readme.md` in `remark-lint-table-pipes`
    ✓ wrote `readme.md` in `remark-lint-unordered-list-marker-style`

    > @ format /home/alex/Projects/js/remark-lint
    > remark . -qfo && prettier --write "**/*.js" && xo --fix

    .remarkrc.js 29ms
    packages/remark-lint-blockquote-indentation/index.js 19ms
    packages/remark-lint-checkbox-character-style/index.js 25ms
    packages/remark-lint-checkbox-content-indent/index.js 15ms
    packages/remark-lint-code-block-style/index.js 11ms
    packages/remark-lint-definition-case/index.js 7ms
    packages/remark-lint-definition-spacing/index.js 8ms
    packages/remark-lint-emphasis-marker/index.js 8ms
    packages/remark-lint-fenced-code-flag/index.js 10ms
    packages/remark-lint-fenced-code-marker/index.js 8ms
    packages/remark-lint-file-extension/index.js 3ms
    packages/remark-lint-final-definition/index.js 5ms
    packages/remark-lint-final-newline/index.js 3ms
    packages/remark-lint-first-heading-level/index.js 7ms
    packages/remark-lint-hard-break-spaces/index.js 6ms
    packages/remark-lint-heading-increment/index.js 5ms
    packages/remark-lint-heading-style/index.js 5ms
    packages/remark-lint-linebreak-style/index.js 11ms
    packages/remark-lint-link-title-style/index.js 15ms
    packages/remark-lint-list-item-bullet-indent/index.js 8ms
    packages/remark-lint-list-item-content-indent/index.js 13ms
    packages/remark-lint-list-item-indent/index.js 10ms
    packages/remark-lint-list-item-spacing/index.js 8ms
    packages/remark-lint-maximum-heading-length/index.js 4ms
    packages/remark-lint-maximum-line-length/index.js 10ms
    packages/remark-lint-no-auto-link-without-protocol/index.js 6ms
    packages/remark-lint-no-blockquote-without-marker/index.js 7ms
    packages/remark-lint-no-consecutive-blank-lines/index.js 10ms
    packages/remark-lint-no-duplicate-defined-urls/index.js 3ms
    packages/remark-lint-no-duplicate-definitions/index.js 4ms
    packages/remark-lint-no-duplicate-headings-in-section/index.js 4ms
    packages/remark-lint-no-duplicate-headings/index.js 3ms
    packages/remark-lint-no-emphasis-as-heading/index.js 3ms
    packages/remark-lint-no-empty-url/index.js 3ms
    packages/remark-lint-no-file-name-articles/index.js 2ms
    packages/remark-lint-no-file-name-consecutive-dashes/index.js 2ms
    packages/remark-lint-no-file-name-irregular-characters/index.js 5ms
    packages/remark-lint-no-file-name-mixed-case/index.js 2ms
    packages/remark-lint-no-file-name-outer-dashes/index.js 2ms
    packages/remark-lint-no-heading-content-indent/index.js 7ms
    packages/remark-lint-no-heading-indent/index.js 4ms
    packages/remark-lint-no-heading-like-paragraph/index.js 5ms
    packages/remark-lint-no-heading-punctuation/index.js 4ms
    packages/remark-lint-no-html/index.js 5ms
    packages/remark-lint-no-inline-padding/index.js 6ms
    packages/remark-lint-no-literal-urls/index.js 4ms
    packages/remark-lint-no-missing-blank-lines/index.js 6ms
    packages/remark-lint-no-multiple-toplevel-headings/index.js 3ms
    packages/remark-lint-no-paragraph-content-indent/index.js 7ms
    packages/remark-lint-no-reference-like-url/index.js 4ms
    packages/remark-lint-no-shell-dollars/index.js 5ms
    packages/remark-lint-no-shortcut-reference-image/index.js 3ms
    packages/remark-lint-no-shortcut-reference-link/index.js 4ms
    packages/remark-lint-no-table-indentation/index.js 3ms
    packages/remark-lint-no-tabs/index.js 3ms
    packages/remark-lint-no-undefined-references/index.js 4ms
    packages/remark-lint-no-unneeded-full-reference-image/index.js 6ms
    packages/remark-lint-no-unneeded-full-reference-link/index.js 3ms
    packages/remark-lint-no-unused-definitions/index.js 3ms
    packages/remark-lint-ordered-list-marker-style/index.js 4ms
    packages/remark-lint-ordered-list-marker-value/index.js 6ms
    packages/remark-lint-rule-style/index.js 5ms
    packages/remark-lint-strong-marker/index.js 7ms
    packages/remark-lint-table-cell-padding/index.js 12ms
    packages/remark-lint-table-pipe-alignment/index.js 11ms
    packages/remark-lint-table-pipes/index.js 7ms
    packages/remark-lint-unordered-list-marker-style/index.js 5ms
    packages/remark-lint/index.js 1ms
    packages/remark-preset-lint-consistent/index.js 4ms
    packages/remark-preset-lint-markdown-style-guide/index.js 8ms
    packages/remark-preset-lint-recommended/index.js 2ms
    packages/unified-lint-rule/index.js 8ms
    script/build-presets.js 52ms
    script/build-rules.js 50ms
    script/characters.js 7ms
    script/plugin/list-of-presets.js 4ms
    script/plugin/list-of-rules.js 6ms
    script/util/find.js 3ms
    script/util/presets.js 1ms
    script/util/rule.js 14ms
    script/util/rules.js 2ms
    test.js 31ms
    Error: Failed to load plugin 'prettier' declared in 'CLIOptions': Cannot find module 'eslint-plugin-prettier'
    Require stack:
    - /home/alex/Projects/js/remark-lint/__placeholder__.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
        at Function.resolve (internal/modules/cjs/helpers.js:78:19)
        at Object.resolve (/home/alex/Projects/js/remark-lint/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
        at ConfigArrayFactory._loadPlugin (/home/alex/Projects/js/remark-lint/node_modules/eslint/lib/cli-engine/config-array-factory.js:959:39)
        at /home/alex/Projects/js/remark-lint/node_modules/eslint/lib/cli-engine/config-array-factory.js:848:33
        at Array.reduce (<anonymous>)
        at ConfigArrayFactory._loadPlugins (/home/alex/Projects/js/remark-lint/node_modules/eslint/lib/cli-engine/config-array-factory.js:844:22)
        at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/alex/Projects/js/remark-lint/node_modules/eslint/lib/cli-engine/config-array-factory.js:667:32)
        at _normalizeObjectConfigDataBody.next (<anonymous>)
        at ConfigArrayFactory._normalizeObjectConfigData (/home/alex/Projects/js/remark-lint/node_modules/eslint/lib/cli-engine/config-array-factory.js:596:20)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! @ format: `remark . -qfo && prettier --write "**/*.js" && xo --fix`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the @ format script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/alex/.npm/_logs/2020-04-19T12_50_44_125Z-debug.log
    error Command failed with exit code 1.
    ```

### Expected behaviour

Tests are running.

### Actual behaviour

Error in tests and unclear documentation.

**Comment by ChristianMurphy** [comment]
@AlexWayfer Most likely this is an issue with either npm/yarn not installing dependencies correctly, rather than an issue with the test suite.


A few indications for this:
1.
```
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/alex/.npm/_logs/2020-04-19T12_46_44_009Z-debug.log
```

2. the tests are passing on CI https://travis-ci.org/github/remarkjs/remark-lint/builds/677573386

---

Is there any additional context in `/home/alex/.npm/_logs/2020-04-19T12_46_44_009Z-debug.log` which describes what was/wasn't installed and any errors encountered?

**Comment by AlexWayfer** [comment]
> Is there any additional context in `/home/alex/.npm/_logs/2020-04-19T12_46_44_009Z-debug.log` which describes what was/wasn't installed and any errors encountered?

The end is like:

```
3653 http fetch GET 200 https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz 31ms (from cache)
3654 silly pacote range manifest for bcrypt-pbkdf@^1.0.0 fetched in 4279ms
3655 silly pacote range manifest for tweetnacl@^0.14.3 fetched in 1ms
3656 http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify 40292ms attempt #2
3657 http fetch GET 200 https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.1.0.tgz 37ms (from cache)
3658 silly pacote range manifest for fast-json-stable-stringify@^2.0.0 fetched in 40331ms
3659 timing npm Completed in 95149ms
3660 error cb() never called!
3661 error This is an error with npm itself. Please report this error at:
3662 error <https://npm.community>
```

Can I get some instructions to set-up development environment please?

**Comment by wooorm** [comment]
Sorry for the wait.

This normally works. For some very weird reason out of our control, npm is broken for you: the error messages state that it’s an error in npm. What makes it extra confusing is that the actual error is swallowed by npm (`cb() never called` isn’t the actual problem). I suggest: [clearing the npm cache](https://docs.npmjs.com/cli-commands/cache.html), installing node/npm again and restarting your system. If that doesn’t work, could you post the full log instead of just the tail?

**Comment by AlexWayfer** [comment]
`npm` from `14.1.0` installed via `asdf` (I'm trying at the same time) has no errors. Sorry.
